export const Users = [
    {
        id: 1,
        profilePicture: "person/1.jpg",
        username: "Miley Cyrus",
    },
    {
        id: 2,
        profilePicture: "person/2.jpg",
        username: "Jannifer Aniston",
    },
    {
        id: 3,
        profilePicture: "person/3.jpg",
        username: "Mila Kunis",
    },
    {
        id: 4,
        profilePicture: "person/4.jpg",
        username: "Angelina Jolie",
    },
    {
        id: 5,
        profilePicture: "person/5.jpg",
        username: "Jannet jackson",
    },
    {
        id: 6,
        profilePicture: "person/6.jpg",
        username: "Jennifer Lawrence",
    },
    {
        id: 7,
        profilePicture: "person/7.jpg",
        username: "Tom Cruise",
    },
    {
        id: 8,
        profilePicture: "person/8.jpg",
        username: "Brad Pitt",
    },

];

export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For none",
        photo: "post/1.jpg",
        date: "5 mins ago",
        userId: 1,
        likes: 4,
        hearts: 32,
        comments: 9, 
    },
    {
        id: 2,
        photo: "post/2.jpg",
        date: "15 mins ago",
        userId: 2,
        likes: 40,
        hearts: 32,
        comments: 6, 
    },
    {
        id: 3,
        desc: "yummy.....!!!",
        photo: "post/3.jpg",
        date: "50 mins ago",
        userId: 3,
        likes: 20,
        hearts: 92,
        comments: 12, 
    },
    {
        id: 4,
        desc: "I have an Orange....wanna share it???",
        photo: "post/4.jpg",
        date: "25 mins ago",
        userId: 4,
        likes: 40,
        hearts: 52,
        comments: 4, 
    },
    {
        id: 5,
        desc: "I have a food family",
        photo: "post/5.jpg",
        date: "35 mins ago",
        userId: 5,
        likes: 25,
        hearts: 30,
        comments: 3, 
    },
    {
        id: 6,
        desc: "Uh.....It's tasty....",
        photo: "post/6.jpg",
        date: "51 mins ago",
        userId: 6,
        likes: 40,
        hearts: 62,
        comments: 7, 
    },
    {
        id: 7,
        desc: "Orange has a Vitamin C, You should all take it, meow",
        photo: "post/7.jpg",
        date: "8 mins ago",
        userId: 7,
        likes: 4,
        hearts: 12,
        comments: 1, 
    },
    {
        id: 8,
        desc: "I love Vitamin C....bow...bow",
        photo: "post/8.jpg",
        date: "1 min ago",
        userId: 8,
        likes: 6,
        hearts: 8,
        comments: 1, 
    },
]